# =============================================================================
# config.py — Global configuration and constants
# =============================================================================
 
MAX_SUGGESTIONS    = 5
NGRAM_CACHE_FILE   = "ngram_model_standalone.json"
USER_LEARNING_FILE = "user_learning.json"
MODEL_VERSION      = "3.0_roberta_dual"
 
# Dataset files — generated by generate_dataset.py / generate_dataset_english.py
FILIPINO_DATASET_FILE = "filipino_dataset.json"
ENGLISH_DATASET_FILE  = "english_dataset.json"
 
# Dwell engine settings
DWELL_POLL_MS  = 50     # how often we update (ms)
DWELL_ENABLED  = True   # can be toggled from Settings
DWELL_MIN_MS   = 600    # ms of continuous hover required to fire