# =============================================================================
# config.py — Global configuration and constants
# =============================================================================
 
MAX_SUGGESTIONS    = 5
NGRAM_CACHE_FILE   = "ngram_model_standalone.json"
USER_LEARNING_FILE = "user_learning.json"
MODEL_VERSION      = "3.0_roberta_dual"
 
# Dataset files — generated by generate_dataset.py / generate_dataset_english.py
FILIPINO_DATASET_FILE = "filipino_dataset.json"
ENGLISH_DATASET_FILE  = "english_dataset.json"
 
# Dwell engine settings
DWELL_POLL_MS  = 50     # how often we update (ms)
DWELL_ENABLED  = True   # can be toggled from Settings
DWELL_MIN_MS   = 1000   # ms of continuous hover required to fire
DWELL_ZOOM          = True  # zoom hovered key as dwell accumulates
DWELL_ZOOM_DELAY_MS  = 300   # ms to wait before zoom starts appearing
DWELL_COOLDOWN_MS    = 800   # ms to pause after a key fires before accepting next input
# "sync"  = accumulative trial window (winner-takes-all at end of trial)
# "async" = zoom-on-dwell (fires as soon as one key hits threshold)
DWELL_MODE     = "sync"