# =============================================================================
# config.py — Global configuration and constants
# =============================================================================
 
import os as _os
_HERE = _os.path.dirname(_os.path.abspath(__file__))

MAX_SUGGESTIONS    = 5
NGRAM_CACHE_FILE   = _os.path.join(_HERE, "ngram_model_standalone.json")
USER_LEARNING_FILE = _os.path.join(_HERE, "user_learning.json")
MODEL_VERSION      = "3.0_roberta_dual"
ENABLE_CNN_PHRASE_SUGGESTIONS = True
CNN_PHRASE_CACHE_FILE = _os.path.join(_HERE, "cnn_phrase_model.pt")
CNN_PHRASE_MAX_CONTEXT = 5
CNN_PHRASE_MAX_RESULTS = 2
CNN_PHRASE_EPOCHS = 12
CNN_PHRASE_RETRAIN_ON_CLOSE = True
ENABLE_LIVE_PHRASE_MEMORY = True
LIVE_PHRASE_MEMORY_MAX_RESULTS = 2
LIVE_PHRASE_MEMORY_MIN_COUNT = 1

# Dataset files — generated by generate_dataset.py / generate_dataset_english.py
FILIPINO_DATASET_FILE = _os.path.join(_HERE, "filipino_dataset.json")
ENGLISH_DATASET_FILE  = _os.path.join(_HERE, "english_dataset.json")
 
# Dwell engine settings
DWELL_POLL_MS  = 50     # how often we update (ms)
DWELL_ENABLED  = True   # can be toggled from Settings
DWELL_MIN_MS   = 1000   # ms of continuous hover required to fire
DWELL_ZOOM          = True  # zoom hovered key as dwell accumulates
DWELL_ZOOM_DELAY_MS  = 300   # ms to wait before zoom starts appearing
DWELL_COOLDOWN_MS    = 800   # ms to pause after a key fires before accepting next input
# "sync"  = accumulative trial window (winner-takes-all at end of trial)
# "async" = zoom-on-dwell (fires as soon as one key hits threshold)
DWELL_MODE     = "sync"

# Prediction language filter
# "both"     = Filipino + English suggestions mixed
# "filipino" = Filipino words only
# "english"  = English words only
PREDICTION_LANGUAGE = "both"
